### ISSUE TITLE
Generate nice release notes

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#533]
# Feature request

Projects like Spring or Mockk have nice Github [release](https://github.com/spring-projects/spring-framework/releases) [notes](https://github.com/mockk/mockk/releases) while CodeCharta [does not](https://github.com/MaibornWolff/codecharta/releases). Our changelog does not appear in the releases Tab at all. 

I assume this is because we did not configure everything according to the [Github specs](https://developer.github.com/v3/repos/releases/#create-a-release). Can we please fix this issue and add nice release notes with funny icons? :)

Also: can we change the most recent release notes to display the correct changelog?

Goals:
* add correct release notes to our releases Tab
* link issues to the correct release

**Comment by NearW** [comment]
If you want to do automatically release, you have to specify a body that is used by travis and that will be attached to the build. So far we never set this body.

```
deploy:
  # releases the built packages on github when a commit is tagged
  - provider: releases
    api_key: $GITHUB_TOKEN
    BODY: MY_RELEVANT_CHANGELOG_INFOS
    file_glob: true
    file:
      - "visualization/dist/packages/*.zip"
      - "analysis/build/distributions/*.tar"
    skip_cleanup: true
    on:
      tags: true
      branch: master
```

We need a .sh-script that returns the latest infos from our changelog and that's where I'm struggling right now.
